name: chat_app
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3
  firebase_auth: ^4.12.1
  firebase_core: ^2.21.0
  cloud_firestore: ^4.12.2
  firebase_storage: ^11.4.1
  firebase_messaging: ^14.7.3
  flutter_facebook_auth: ^6.0.2
  google_sign_in: ^6.1.5
  dio: ^5.3.3
  http: ^1.1.0
  chopper: ^7.0.9
  flutter_screenutil: ^5.9.0
  lottie: ^2.7.0
  image_picker: ^1.0.4
  file_picker: ^6.0.0
  freezed_annotation: ^2.4.1
  flutter_svg: ^2.0.9
  freezed: ^2.4.5
  font_awesome_flutter: ^10.6.0
  get_it: ^7.6.4
  equatable: ^2.0.5
  animated_text_kit: ^4.2.2
  auto_size_text: ^3.0.0
  internet_connection_checker: ^1.0.0+1
  flutter_offline: ^3.0.0
  hive: ^2.2.3
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  cached_network_image: ^3.3.0
  permission_handler: ^11.0.1


flutter_assets:
  assets_path: assets/images/
  output_path: lib/constants/
  filename: app_images.dart
  field_prefix:


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true


  assets:
    - assets/images/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-Bold.ttf
        - asset: assets/fonts/nunito/Nunito-Regular.ttf

