// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdaejemyMhVH4SSBJXKUMMJxZIJ18wiGY',
    appId: '1:395238789519:web:a344ac64b41d29e50f3bfa',
    messagingSenderId: '395238789519',
    projectId: 'mychatapp-9bae4',
    authDomain: 'mychatapp-9bae4.firebaseapp.com',
    storageBucket: 'mychatapp-9bae4.appspot.com',
    measurementId: 'G-WECWVE1KE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6klwggD9yD0BfELQtHnEtddtELDnNZpw',
    appId: '1:395238789519:android:2c7279e60aedc6b40f3bfa',
    messagingSenderId: '395238789519',
    projectId: 'mychatapp-9bae4',
    storageBucket: 'mychatapp-9bae4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKTeyW0XVRNopNdo42-tlmIAkrjPLmkGc',
    appId: '1:395238789519:ios:e5d1c67aa1e2e4570f3bfa',
    messagingSenderId: '395238789519',
    projectId: 'mychatapp-9bae4',
    storageBucket: 'mychatapp-9bae4.appspot.com',
    androidClientId: '395238789519-q434ebd5q6kpl7jhd1ad0t5urpj5kgce.apps.googleusercontent.com',
    iosClientId: '395238789519-ue1vnj8cpergvl6rtu1t0cinqktfjjav.apps.googleusercontent.com',
    iosBundleId: 'com.example.myChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKTeyW0XVRNopNdo42-tlmIAkrjPLmkGc',
    appId: '1:395238789519:ios:4f80701a40b3f4930f3bfa',
    messagingSenderId: '395238789519',
    projectId: 'mychatapp-9bae4',
    storageBucket: 'mychatapp-9bae4.appspot.com',
    androidClientId: '395238789519-q434ebd5q6kpl7jhd1ad0t5urpj5kgce.apps.googleusercontent.com',
    iosClientId: '395238789519-80om87po51hd11v3m767sk5geb46kucf.apps.googleusercontent.com',
    iosBundleId: 'com.example.myChatApp.RunnerTests',
  );
}
